### ISSUE TITLE
Metallic GTK3.20 theme isn't the same

### ISSUE THREAD

**Issue by jacobpoo** [B00merang-Project/WinXP-themes#1]
The Metallic GTK3.20 theme needs to be the same if you can...

**Comment by Elbullazul** [comment]
@jacobpoo screenshot please? I just recompiled everything in a new model, so I'm waiting to see at least 3 or 4 bugs

**Comment by jacobpoo** [comment]
![image](https://cloud.githubusercontent.com/assets/24438557/22311948/da9e2ab8-e323-11e6-9b54-918822a44b1c.png)

**Comment by Elbullazul** [comment]
think I fixed it
