### ISSUE TITLE
bashrc help

### ISSUE THREAD

**Issue by jacobpoo** [B00merang-Project/WinXP-themes#2]
@Elbullazul On the screenshot, the bash prompt looks like cmd, how do I do that?

**Comment by Elbullazul** [comment]
@jacobpoo it's a small shell script I made, only for screenshooting.

however, I understand you can change how bash looks by placing this at the end of your bashrc

PS1="C:\\w/>"

**Comment by jacobpoo** [comment]
@thanks

**Comment by jacobpoo** [comment]
@Elbullazul thanks

**Comment by feren** [comment]
@jacobpoo Or, you could look at Chicago95's one, and change the "DOS" labels on the top to match XPs

**Comment by jacobpoo** [comment]
@feren true

**Comment by jacobpoo** [comment]
![screenshot_2017-06-30_17-32-12](https://user-images.githubusercontent.com/24438557/27754770-1abd078e-5dba-11e7-91b0-a31aa6b8594f.png)
